# Generated by Django 3.2.5 on 2021-07-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production_pvrmt',
            old_name='Charge',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='production_pvrmt',
            old_name='Decharge',
            new_name='decharge',
        ),
    ]
