# Generated by Django 3.2.5 on 2021-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('hourfc', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, db_column='Humidity', null=True)),
                ('pressure', models.IntegerField(blank=True, db_column='Pressure', null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='Temperature', decimal_places=2, max_digits=4, null=True)),
                ('dew_point', models.DecimalField(blank=True, db_column='Dew_point', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'ems',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='production_pvrmt',
        ),
    ]
