# Generated by Django 3.2.5 on 2021-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211128_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ems',
            name='numero',
        ),
        migrations.AlterField(
            model_name='ems',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
